[build]
  command = "python heart.py"  # Update with your Flask app's build command
  publish = "templates"  # Update with the directory containing your templates
[[redirects]]
  from = "/index.html"
  to = "/templates/index.html"
  status = 200

[[redirects]]
  from = "/result.html"
  to = "/templates/result.html"
  status = 200

