# netlify.toml

# Build settings
[build]
  # Build command
  command = "python build_heart.py"  # Replace with your build command






# Optional: Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200



